services:
  - name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: backend

  - name: frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
